# Generated by Django 5.2.7 on 2025-11-04 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('diet_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.dietlog')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('focus', models.CharField(blank=True, help_text="e.g., 'Chest, Back, Legs'", max_length=255, null=True)),
                ('exercises', models.TextField(blank=True, help_text='e.g., Bench Press\n3 sets x 8-10 reps', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
