# core/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# The router automatically generates the API routes
router = DefaultRouter()
router.register('register', views.CreateUserViewSet, basename='register')
router.register('dietlogs', views.DietLogViewSet, basename='dietlogs')
router.register('fooditems', views.FoodItemViewSet, basename='fooditems')
router.register('exercises', views.ExerciseViewSet, basename='exercises')
router.register('sets', views.WorkoutSetViewSet, basename='sets')

app_name = 'core'

urlpatterns = [
    # This path is for getting a login token
    path('token/', views.CreateTokenView.as_view(), name='token'),
    # ADD THIS NEW LINE
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    # This includes all the routes generated by the router
    path('', include(router.urls)),
]
